//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rediin2022.Entidades.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesXId {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesXId() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rediin2022.Entidades.Idioma.MensajesXId", typeof(MensajesXId).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización.
        /// </summary>
        public static string _AutorizacionTitCap {
            get {
                return ResourceManager.GetString("_AutorizacionTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizaciones.
        /// </summary>
        public static string _AutorizacionTitCon {
            get {
                return ResourceManager.GetString("_AutorizacionTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string _AutorizacionUsuarioInicia {
            get {
                return ResourceManager.GetString("_AutorizacionUsuarioInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string _AutorizacionUsuarioTitCap {
            get {
                return ResourceManager.GetString("_AutorizacionUsuarioTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string _AutorizacionUsuarioTitCon {
            get {
                return ResourceManager.GetString("_AutorizacionUsuarioTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string _BancoTitCap {
            get {
                return ResourceManager.GetString("_BancoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string _BancoTitCon {
            get {
                return ResourceManager.GetString("_BancoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios..
        /// </summary>
        public static string _ConExpedienteCambioEstatusTitCap {
            get {
                return ResourceManager.GetString("_ConExpedienteCambioEstatusTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expedientes.
        /// </summary>
        public static string _ConExpedienteInicia {
            get {
                return ResourceManager.GetString("_ConExpedienteInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos.
        /// </summary>
        public static string _ConExpedienteObjetoInicia {
            get {
                return ResourceManager.GetString("_ConExpedienteObjetoInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar el archivo.
        /// </summary>
        public static string _ConExpedienteObjetoSelArchivoTitCap {
            get {
                return ResourceManager.GetString("_ConExpedienteObjetoSelArchivoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expediente objeto.
        /// </summary>
        public static string _ConExpedienteObjetoTitCap {
            get {
                return ResourceManager.GetString("_ConExpedienteObjetoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expedientes/Objetos.
        /// </summary>
        public static string _ConExpedienteObjetoTitCon {
            get {
                return ResourceManager.GetString("_ConExpedienteObjetoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expediente.
        /// </summary>
        public static string _ConExpedienteTitCap {
            get {
                return ResourceManager.GetString("_ConExpedienteTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expedientes.
        /// </summary>
        public static string _ConExpedienteTitCon {
            get {
                return ResourceManager.GetString("_ConExpedienteTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expedientes/Procesos operativos.
        /// </summary>
        public static string _ConExpProcOperativoTitCon {
            get {
                return ResourceManager.GetString("_ConExpProcOperativoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ExpedienteEstatuInicia {
            get {
                return ResourceManager.GetString("_ExpedienteEstatuInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ExpedienteEstatuTitCap {
            get {
                return ResourceManager.GetString("_ExpedienteEstatuTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ExpedienteEstatuTitCon {
            get {
                return ResourceManager.GetString("_ExpedienteEstatuTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificacion.
        /// </summary>
        public static string _IdentificacionTitCap {
            get {
                return ResourceManager.GetString("_IdentificacionTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificaciones.
        /// </summary>
        public static string _IdentificacionTitCon {
            get {
                return ResourceManager.GetString("_IdentificacionTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoterm.
        /// </summary>
        public static string _IncotermTitCap {
            get {
                return ResourceManager.GetString("_IncotermTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoterms.
        /// </summary>
        public static string _IncotermTitCon {
            get {
                return ResourceManager.GetString("_IncotermTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string _ModeloTitCap {
            get {
                return ResourceManager.GetString("_ModeloTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelos.
        /// </summary>
        public static string _ModeloTitCon {
            get {
                return ResourceManager.GetString("_ModeloTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas.
        /// </summary>
        public static string _ProcesoOperativoColInicia {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        public static string _ProcesoOperativoColST1 {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Captura.
        /// </summary>
        public static string _ProcesoOperativoColST2 {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combo (opcional).
        /// </summary>
        public static string _ProcesoOperativoColST3 {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColST3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna.
        /// </summary>
        public static string _ProcesoOperativoColTitCap {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos operativos/Columnas.
        /// </summary>
        public static string _ProcesoOperativoColTitCon {
            get {
                return ResourceManager.GetString("_ProcesoOperativoColTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ProcesoOperativoEstInicia {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secuencia.
        /// </summary>
        public static string _ProcesoOperativoEstSecInicia {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstSecInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secuencia.
        /// </summary>
        public static string _ProcesoOperativoEstSecTitCap {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstSecTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secuencia.
        /// </summary>
        public static string _ProcesoOperativoEstSecTitCon {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstSecTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ProcesoOperativoEstTitCap {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string _ProcesoOperativoEstTitCon {
            get {
                return ResourceManager.GetString("_ProcesoOperativoEstTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos.
        /// </summary>
        public static string _ProcesoOperativoObjetoInicia {
            get {
                return ResourceManager.GetString("_ProcesoOperativoObjetoInicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto.
        /// </summary>
        public static string _ProcesoOperativoObjetoTitCap {
            get {
                return ResourceManager.GetString("_ProcesoOperativoObjetoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos operativos/Objetos.
        /// </summary>
        public static string _ProcesoOperativoObjetoTitCon {
            get {
                return ResourceManager.GetString("_ProcesoOperativoObjetoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso operativo.
        /// </summary>
        public static string _ProcesoOperativoTitCap {
            get {
                return ResourceManager.GetString("_ProcesoOperativoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogos/Procesos operativos.
        /// </summary>
        public static string _ProcesoOperativoTitCon {
            get {
                return ResourceManager.GetString("_ProcesoOperativoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen fiscal.
        /// </summary>
        public static string _RegimenFiscalTitCap {
            get {
                return ResourceManager.GetString("_RegimenFiscalTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimenes fiscales.
        /// </summary>
        public static string _RegimenFiscalTitCon {
            get {
                return ResourceManager.GetString("_RegimenFiscalTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string _SapBancoTitCap {
            get {
                return ResourceManager.GetString("_SapBancoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string _SapBancoTitCon {
            get {
                return ResourceManager.GetString("_SapBancoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición de pago.
        /// </summary>
        public static string _SapCondicionPagoTitCap {
            get {
                return ResourceManager.GetString("_SapCondicionPagoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones pago.
        /// </summary>
        public static string _SapCondicionPagoTitCon {
            get {
                return ResourceManager.GetString("_SapCondicionPagoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta asociada.
        /// </summary>
        public static string _SapCuentaAsociadaTitCap {
            get {
                return ResourceManager.GetString("_SapCuentaAsociadaTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas asociadas.
        /// </summary>
        public static string _SapCuentaAsociadaTitCon {
            get {
                return ResourceManager.GetString("_SapCuentaAsociadaTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de cuenta.
        /// </summary>
        public static string _SapGrupoCuentaTitCap {
            get {
                return ResourceManager.GetString("_SapGrupoCuentaTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de cuentas.
        /// </summary>
        public static string _SapGrupoCuentaTitCon {
            get {
                return ResourceManager.GetString("_SapGrupoCuentaTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de tesorería.
        /// </summary>
        public static string _SapGrupoTesoreriaTitCap {
            get {
                return ResourceManager.GetString("_SapGrupoTesoreriaTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de tesorería.
        /// </summary>
        public static string _SapGrupoTesoreriaTitCon {
            get {
                return ResourceManager.GetString("_SapGrupoTesoreriaTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de tolerancia.
        /// </summary>
        public static string _SapGrupoToleranciaTitCap {
            get {
                return ResourceManager.GetString("_SapGrupoToleranciaTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de tolerancia.
        /// </summary>
        public static string _SapGrupoToleranciaTitCon {
            get {
                return ResourceManager.GetString("_SapGrupoToleranciaTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organización de compra.
        /// </summary>
        public static string _SapOrganizacionCompraTitCap {
            get {
                return ResourceManager.GetString("_SapOrganizacionCompraTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organizaciones de compra.
        /// </summary>
        public static string _SapOrganizacionCompraTitCon {
            get {
                return ResourceManager.GetString("_SapOrganizacionCompraTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad GL.
        /// </summary>
        public static string _SapSociedadGLTitCap {
            get {
                return ResourceManager.GetString("_SapSociedadGLTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedades GL.
        /// </summary>
        public static string _SapSociedadGLTitCon {
            get {
                return ResourceManager.GetString("_SapSociedadGLTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad.
        /// </summary>
        public static string _SapSociedadTitCap {
            get {
                return ResourceManager.GetString("_SapSociedadTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedades.
        /// </summary>
        public static string _SapSociedadTitCon {
            get {
                return ResourceManager.GetString("_SapSociedadTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamiento.
        /// </summary>
        public static string _SapTratamientoTitCap {
            get {
                return ResourceManager.GetString("_SapTratamientoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamientos.
        /// </summary>
        public static string _SapTratamientoTitCon {
            get {
                return ResourceManager.GetString("_SapTratamientoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vía de pago.
        /// </summary>
        public static string _SapViaPagoTitCap {
            get {
                return ResourceManager.GetString("_SapViaPagoTitCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vías de pago.
        /// </summary>
        public static string _SapViaPagoTitCon {
            get {
                return ResourceManager.GetString("_SapViaPagoTitCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string ApellidoMaterno {
            get {
                return ResourceManager.GetString("ApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string ApellidoPaterno {
            get {
                return ResourceManager.GetString("ApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string ArchivoNombre {
            get {
                return ResourceManager.GetString("ArchivoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve autorización.
        /// </summary>
        public static string AutorizacionId {
            get {
                return ResourceManager.GetString("AutorizacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string AutorizacionNombre {
            get {
                return ResourceManager.GetString("AutorizacionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        public static string AutorizacionUsuarioId {
            get {
                return ResourceManager.GetString("AutorizacionUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve banco.
        /// </summary>
        public static string BancoId {
            get {
                return ResourceManager.GetString("BancoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string BancoNombre {
            get {
                return ResourceManager.GetString("BancoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscador.
        /// </summary>
        public static string BusquedaTexto {
            get {
                return ResourceManager.GetString("BusquedaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna Cve.
        /// </summary>
        public static string CapCmbIdColumnaId {
            get {
                return ResourceManager.GetString("CapCmbIdColumnaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve proc. oper. catálogo.
        /// </summary>
        public static string CapCmbProcesoOperativoId {
            get {
                return ResourceManager.GetString("CapCmbProcesoOperativoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna Texto.
        /// </summary>
        public static string CapCmbTextoColumnaId {
            get {
                return ResourceManager.GetString("CapCmbTextoColumnaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas de captura.
        /// </summary>
        public static string CapColumnas {
            get {
                return ResourceManager.GetString("CapColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas vacias.
        /// </summary>
        public static string CapColumnasVacias {
            get {
                return ResourceManager.GetString("CapColumnasVacias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obligatorio.
        /// </summary>
        public static string CapObligatorio {
            get {
                return ResourceManager.GetString("CapObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden en captura.
        /// </summary>
        public static string CapOrden {
            get {
                return ResourceManager.GetString("CapOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango final.
        /// </summary>
        public static string CapRangoFin {
            get {
                return ResourceManager.GetString("CapRangoFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango inicial.
        /// </summary>
        public static string CapRangoIni {
            get {
                return ResourceManager.GetString("CapRangoIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabulador.
        /// </summary>
        public static string CapTab {
            get {
                return ResourceManager.GetString("CapTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. columna.
        /// </summary>
        public static string ColumnaId {
            get {
                return ResourceManager.GetString("ColumnaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve combo.
        /// </summary>
        public static string ComboId {
            get {
                return ResourceManager.GetString("ComboId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string ConLongitud {
            get {
                return ResourceManager.GetString("ConLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden en consulta.
        /// </summary>
        public static string ConOrden {
            get {
                return ResourceManager.GetString("ConOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite ordenar.
        /// </summary>
        public static string ConOrdenar {
            get {
                return ResourceManager.GetString("ConOrdenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control por estatus.
        /// </summary>
        public static string ControlEstatus {
            get {
                return ResourceManager.GetString("ControlEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimales.
        /// </summary>
        public static string Decimales {
            get {
                return ResourceManager.GetString("Decimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días vencimiento.
        /// </summary>
        public static string DiasVencimiento {
            get {
                return ResourceManager.GetString("DiasVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es catálogo.
        /// </summary>
        public static string EsCatalogo {
            get {
                return ResourceManager.GetString("EsCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esquema objetos.
        /// </summary>
        public static string EsquemaObjetos {
            get {
                return ResourceManager.GetString("EsquemaObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve establecimiento.
        /// </summary>
        public static string EstablecimientoId {
            get {
                return ResourceManager.GetString("EstablecimientoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Establecimiento.
        /// </summary>
        public static string EstablecimientoNombre {
            get {
                return ResourceManager.GetString("EstablecimientoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string EstatusNombre {
            get {
                return ResourceManager.GetString("EstatusNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string EstatusNombreSig {
            get {
                return ResourceManager.GetString("EstatusNombreSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiqueta.
        /// </summary>
        public static string Etiqueta {
            get {
                return ResourceManager.GetString("Etiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve expediente.
        /// </summary>
        public static string ExpedienteId {
            get {
                return ResourceManager.GetString("ExpedienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve expediente objeto.
        /// </summary>
        public static string ExpedienteObjetoId {
            get {
                return ResourceManager.GetString("ExpedienteObjetoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve identificación.
        /// </summary>
        public static string IdentificacionId {
            get {
                return ResourceManager.GetString("IdentificacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string IdentificacionNombre {
            get {
                return ResourceManager.GetString("IdentificacionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Incoterm.
        /// </summary>
        public static string IncotermClave {
            get {
                return ResourceManager.GetString("IncotermClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incoterm.
        /// </summary>
        public static string IncotermId {
            get {
                return ResourceManager.GetString("IncotermId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoterm.
        /// </summary>
        public static string IncotermNombre {
            get {
                return ResourceManager.GetString("IncotermNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve modelo.
        /// </summary>
        public static string ModeloId {
            get {
                return ResourceManager.GetString("ModeloId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string ModeloNombre {
            get {
                return ResourceManager.GetString("ModeloNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obligatorio.
        /// </summary>
        public static string Obligatorio {
            get {
                return ResourceManager.GetString("Obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite modificar.
        /// </summary>
        public static string PermiteModificar {
            get {
                return ResourceManager.GetString("PermiteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve estatus.
        /// </summary>
        public static string ProcesoOperativoEstId {
            get {
                return ResourceManager.GetString("ProcesoOperativoEstId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string ProcesoOperativoEstIdSig {
            get {
                return ResourceManager.GetString("ProcesoOperativoEstIdSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve secuencia.
        /// </summary>
        public static string ProcesoOperativoEstSecId {
            get {
                return ResourceManager.GetString("ProcesoOperativoEstSecId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. proceso.
        /// </summary>
        public static string ProcesoOperativoId {
            get {
                return ResourceManager.GetString("ProcesoOperativoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso operativo.
        /// </summary>
        public static string ProcesoOperativoNombre {
            get {
                return ResourceManager.GetString("ProcesoOperativoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. objeto.
        /// </summary>
        public static string ProcesoOperativoObjetoId {
            get {
                return ResourceManager.GetString("ProcesoOperativoObjetoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ProcesoOperativoObjetoNombre {
            get {
                return ResourceManager.GetString("ProcesoOperativoObjetoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Régimen.
        /// </summary>
        public static string RegimenFiscaId {
            get {
                return ResourceManager.GetString("RegimenFiscaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Régimen.
        /// </summary>
        public static string RegimenFiscalClave {
            get {
                return ResourceManager.GetString("RegimenFiscalClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen fiscal.
        /// </summary>
        public static string RegimenFiscalNombre {
            get {
                return ResourceManager.GetString("RegimenFiscalNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        public static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Banco.
        /// </summary>
        public static string SapBancoId {
            get {
                return ResourceManager.GetString("SapBancoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string SapBancoNombre {
            get {
                return ResourceManager.GetString("SapBancoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve condición de pago.
        /// </summary>
        public static string SapCondicionPagoId {
            get {
                return ResourceManager.GetString("SapCondicionPagoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición de pago.
        /// </summary>
        public static string SapCondicionPagoNombre {
            get {
                return ResourceManager.GetString("SapCondicionPagoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Cuenta asociada.
        /// </summary>
        public static string SapCuentaAsociadaId {
            get {
                return ResourceManager.GetString("SapCuentaAsociadaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta asociada.
        /// </summary>
        public static string SapCuentaAsociadaNombre {
            get {
                return ResourceManager.GetString("SapCuentaAsociadaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Grupo de cuenta.
        /// </summary>
        public static string SapGrupoCuentaId {
            get {
                return ResourceManager.GetString("SapGrupoCuentaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de cuenta.
        /// </summary>
        public static string SapGrupoCuentaNombre {
            get {
                return ResourceManager.GetString("SapGrupoCuentaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Grupo de tesorería.
        /// </summary>
        public static string SapGrupoTesoreriaId {
            get {
                return ResourceManager.GetString("SapGrupoTesoreriaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de tesorería.
        /// </summary>
        public static string SapGrupoTesoreriaNombre {
            get {
                return ResourceManager.GetString("SapGrupoTesoreriaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Grupo tolerancia.
        /// </summary>
        public static string SapGrupoToleranciaId {
            get {
                return ResourceManager.GetString("SapGrupoToleranciaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo de tolerancia.
        /// </summary>
        public static string SapGrupoToleranciaNombre {
            get {
                return ResourceManager.GetString("SapGrupoToleranciaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Organización de compra.
        /// </summary>
        public static string SapOrganizacionCompraId {
            get {
                return ResourceManager.GetString("SapOrganizacionCompraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organización de compra.
        /// </summary>
        public static string SapOrganizacionCompraNombre {
            get {
                return ResourceManager.GetString("SapOrganizacionCompraNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Sociedad GL.
        /// </summary>
        public static string SapSociedadGLId {
            get {
                return ResourceManager.GetString("SapSociedadGLId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad GL.
        /// </summary>
        public static string SapSociedadGLNombre {
            get {
                return ResourceManager.GetString("SapSociedadGLNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Sociedad.
        /// </summary>
        public static string SapSociedadId {
            get {
                return ResourceManager.GetString("SapSociedadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad.
        /// </summary>
        public static string SapSociedadNombre {
            get {
                return ResourceManager.GetString("SapSociedadNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Tratamiento.
        /// </summary>
        public static string SapTratamientoId {
            get {
                return ResourceManager.GetString("SapTratamientoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tratamiento.
        /// </summary>
        public static string SapTratamientoNombre {
            get {
                return ResourceManager.GetString("SapTratamientoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve Vía de pago.
        /// </summary>
        public static string SapViaPagoId {
            get {
                return ResourceManager.GetString("SapViaPagoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vía de pago.
        /// </summary>
        public static string SapViaPagoNombre {
            get {
                return ResourceManager.GetString("SapViaPagoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene expedientes.
        /// </summary>
        public static string TieneExpedientes {
            get {
                return ResourceManager.GetString("TieneExpedientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de captura.
        /// </summary>
        public static string TipoCaptura {
            get {
                return ResourceManager.GetString("TipoCaptura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enumerador vacío.
        /// </summary>
        public static string TipoCaptura_Ninguno {
            get {
                return ResourceManager.GetString("TipoCaptura_Ninguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona Extranjera.
        /// </summary>
        public static string TipoCaptura_PersonaExtranjera {
            get {
                return ResourceManager.GetString("TipoCaptura_PersonaExtranjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Person Física.
        /// </summary>
        public static string TipoCaptura_PersonaFisica {
            get {
                return ResourceManager.GetString("TipoCaptura_PersonaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona Moral.
        /// </summary>
        public static string TipoCaptura_PersonaMoral {
            get {
                return ResourceManager.GetString("TipoCaptura_PersonaMoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de captura.
        /// </summary>
        public static string TipoCapturaId {
            get {
                return ResourceManager.GetString("TipoCapturaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de columna.
        /// </summary>
        public static string TiposColumna {
            get {
                return ResourceManager.GetString("TiposColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boleano.
        /// </summary>
        public static string TiposColumna_Boleano {
            get {
                return ResourceManager.GetString("TiposColumna_Boleano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entero.
        /// </summary>
        public static string TiposColumna_Entero {
            get {
                return ResourceManager.GetString("TiposColumna_Entero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string TiposColumna_Fecha {
            get {
                return ResourceManager.GetString("TiposColumna_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaYHora.
        /// </summary>
        public static string TiposColumna_FechaYHora {
            get {
                return ResourceManager.GetString("TiposColumna_FechaYHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string TiposColumna_Hora {
            get {
                return ResourceManager.GetString("TiposColumna_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe.
        /// </summary>
        public static string TiposColumna_Importe {
            get {
                return ResourceManager.GetString("TiposColumna_Importe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enumerador vacío.
        /// </summary>
        public static string TiposColumna_Ninguno {
            get {
                return ResourceManager.GetString("TiposColumna_Ninguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string TiposColumna_Texto {
            get {
                return ResourceManager.GetString("TiposColumna_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve usuario.
        /// </summary>
        public static string UsuarioId {
            get {
                return ResourceManager.GetString("UsuarioId", resourceCulture);
            }
        }
    }
}
